-- 조건 1. car_type이 세단 or suv
-- 조건 2. 대여기간은 22년 11월 한달 대여 가능 -> START_DATE, END_DATE 11월 기록이 X
-- 조건 3. 대여 금액이 50~200

SELECT CRCC.CAR_ID
    , CRCC.CAR_TYPE
    , CRCC.DAILY_FEE * 30 * ((100 - CRCDP.DISCOUNT_RATE) * 0.01) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CRCC
JOIN (
    SELECT * 
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
    WHERE DURATION_TYPE = '30일 이상'
) CRCDP
ON CRCC.CAR_TYPE = CRCDP.CAR_TYPE
WHERE CRCC.CAR_TYPE IN ('세단', 'SUV')
AND CRCC.CAR_ID NOT IN (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= TO_DATE('2022-11-30', 'YYYY-MM-DD')
    AND END_DATE >= TO_DATE('2022-11-01', 'YYYY-MM-DD')
)
AND CRCC.DAILY_FEE * 30 * ((100 - CRCDP.DISCOUNT_RATE) * 0.01) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CRCC.CAR_TYPE, CRCC.CAR_ID DESC
