SELECT ri.FOOD_TYPE, ri.REST_ID, ri.REST_NAME, ri.FAVORITES
FROM REST_INFO ri
JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
        FROM REST_INFO
        GROUP BY FOOD_TYPE
      ) a
ON ri.FOOD_TYPE = a.FOOD_TYPE
WHERE ri.FAVORITES = a.FAVORITES
ORDER BY ri.FOOD_TYPE DESC
;