SELECT AO.ANIMAL_ID, AO.ANIMAL_TYPE, AO.NAME
FROM ANIMAL_OUTS AO
JOIN (
    SELECT * FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE LIKE 'Intact%'
) AI
ON AO.ANIMAL_ID = AI.ANIMAL_ID
WHERE SEX_UPON_OUTCOME NOT LIKE 'Intact%'
ORDER BY AO.ANIMAL_ID