SELECT rr.REST_ID
    ,ri.REST_NAME
    ,ri.FOOD_TYPE
    ,ri.FAVORITES
    ,ri.ADDRESS
    ,ROUND(AVG(rr.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO ri
JOIN REST_REVIEW rr
    ON ri.REST_ID = rr.REST_ID
WHERE ri.ADDRESS LIKE '서울%'
GROUP BY rr.REST_ID
    ,ri.REST_NAME
    ,ri.FOOD_TYPE
    ,ri.FAVORITES
    ,ri.ADDRESS
ORDER BY SCORE DESC, ri.FAVORITES DESC


-- SELECT rr.REST_ID
--     ,ri.REST_NAME
--     ,ri.FOOD_TYPE
--     ,ri.FAVORITES
--     ,ri.ADDRESS
--     ,rr.REVIEW_SCORE
-- FROM REST_INFO ri, REST_REVIEW rr
-- WHERE ri.REST_ID = rr.REST_ID
-- AND ri.ADDRESS LIKE '서울%'