SELECT EXTRACT(YEAR FROM SALES_DATE) AS YEAR
      ,EXTRACT(MONTH FROM SALES_DATE) AS MONTH
      ,COUNT(DISTINCT(OS.USER_ID)) AS PURCHASED_USERS
      ,ROUND(
          COUNT(DISTINCT(OS.USER_ID)) 
          / (
                SELECT COUNT(*) FROM USER_INFO
                WHERE JOINED 
                    BETWEEN TO_DATE('2021-01-01', 'YYYY-MM-DD') 
                    AND TO_DATE('2021-12-31', 'YYYY-MM-DD')
              )
          , 1) AS PUCHASED_RATIO
FROM ONLINE_SALE OS
JOIN (
        SELECT USER_ID
        FROM USER_INFO
        WHERE JOINED BETWEEN TO_DATE('2021-01-01', 'YYYY-MM-DD')
            AND TO_DATE('2021-12-31', 'YYYY-MM-DD')
     ) UI
ON OS.USER_ID = UI.USER_ID
GROUP BY EXTRACT(YEAR FROM SALES_DATE),  EXTRACT(MONTH FROM SALES_DATE)
ORDER BY YEAR, MONTH 

--21년에 가입한 전체 회원 수
-- SELECT COUNT(*) AS TOTAL_USER_CNT
-- FROM USER_INFO
-- WHERE JOINED BETWEEN TO_DATE('2021-01-01', 'YYYY-MM-DD')
--     AND TO_DATE('2021-12-31', 'YYYY-MM-DD')