# 각 세대별 자식이 없는 개체의 수
# where parent_id = 1 결과 행 수가 없어야 함

# where parent_id not in (select id from 부모테이블) ? not exists

   
WITH RECURSIVE GENERATION_CNT_CTE AS (
  # 1세대
  SELECT ID, 1 AS GENERATION, PARENT_ID
  FROM ECOLI_DATA
  WHERE PARENT_ID IS NULL

  UNION ALL
    
  SELECT ED.ID, GCC.GENERATION + 1, ED.PARENT_ID
  FROM ECOLI_DATA ED
  JOIN GENERATION_CNT_CTE GCC ON ED.PARENT_ID = GCC.ID

)
SELECT
  COUNT(*) AS `COUNT`,
  G.GENERATION
FROM (
    SELECT
        G1.ID,
        G1.GENERATION
    FROM 
        GENERATION_CNT_CTE G1
    LEFT JOIN ECOLI_DATA G2 ON G1.ID = G2.PARENT_ID
    GROUP BY G1.ID, G1.GENERATION
    HAVING COUNT(G2.ID) = 0
) G
GROUP BY G.GENERATION
ORDER BY G.GENERATION ASC