SELECT FR.PRODUCT_ID
    , FR.PRODUCT_NAME
    , TOTAL_AMOUNT * FR.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT FR
JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE BETWEEN TO_DATE('2022-05-01', 'YYYY-MM-DD')
    AND TO_DATE('2022-05-31', 'YYYY-MM-DD')
    GROUP BY PRODUCT_ID
) FO
ON FR.PRODUCT_ID = FO.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FR.PRODUCT_ID
;


