-- 같은 맛으로 여러번 출하함
--7월 맛: 초콜릿, 바닐라, 민트초코, 카라멜, 화이트초코, 피치, 딸기
--상반기 맛: 초콜릿, 바닐라, 민트초코, 카라멜, 화이트초코, 피치, 딸기

SELECT FLAVOR
FROM (
    SELECT FH.FLAVOR, FH.TOTAL_ORDER + JULY_TOTAL_ORDER AS SUM_ORDER
    FROM FIRST_HALF FH
    JOIN (
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_TOTAL_ORDER
        FROM JULY
        GROUP BY FLAVOR
    ) J
    ON FH.FLAVOR = J.FLAVOR
    ORDER BY SUM_ORDER DESC
)
WHERE ROWNUM <= 3

-- SELECT FH.FLAVOR, FH.TOTAL_ORDER + JULY_TOTAL_ORDER AS SUM_ORDER
-- FROM FIRST_HALF FH
-- JOIN (
--     SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_TOTAL_ORDER
--     FROM JULY
--     GROUP BY FLAVOR
-- ) J
-- ON FH.FLAVOR = J.FLAVOR
-- ORDER BY SUM_ORDER DESC