SELECT ugu.USER_ID, ugu.NICKNAME, SUM(ugb.PRICE) AS "TOTAL_SALES"
FROM USED_GOODS_USER ugu
JOIN USED_GOODS_BOARD ugb
    ON ugu.USER_ID = ugb.WRITER_ID
WHERE ugb.STATUS = 'DONE'
GROUP BY ugu.USER_ID, ugu.NICKNAME
HAVING SUM(ugb.PRICE) >= 700000
ORDER BY TOTAL_SALES
;