WITH MAX_REVIEW_MEMBER_ID AS (
    SELECT RR.MEMBER_ID,
           RANK() OVER (ORDER BY COUNT(RR.MEMBER_ID) DESC) AS RANKING
    FROM REST_REVIEW RR
    GROUP BY RR.MEMBER_ID
)
SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, TO_CHAR(RR.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM REST_REVIEW RR
JOIN MEMBER_PROFILE MP
ON RR.MEMBER_ID = MP.MEMBER_ID
WHERE RR.MEMBER_ID IN (
                        SELECT MEMBER_ID
                        FROM MAX_REVIEW_MEMBER_ID
                        WHERE RANKING = 1
                      )
ORDER BY RR.REVIEW_DATE, RR.REVIEW_TEXT;
