# 8월부터 10월까지 총 대여 횟수가 5회 이상인 자동차
# SELECT CAR_ID, MONTH(START_DATE), COUNT(*)
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE EXTRACT(YEAR_MONTH FROM START_DATE) BETWEEN 202208 AND 202210
# GROUP BY CAR_ID
# HAVING COUNT(*)  >= 5


# SELECT START_MONTH, CAR_ID, COUNT(*) AS RECORDS
# FROM (
#     SELECT CAR_ID, MONTH(START_DATE) AS START_MONTH, COUNT(*)
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE EXTRACT(YEAR_MONTH FROM START_DATE) BETWEEN 202208 AND 202210
#     GROUP BY CAR_ID
#     HAVING COUNT(*)  >= 5
# ) AS CAR
# GROUP BY CAR.START_MONTH, CAR.CAR_ID
# ORDER BY CAR.START_MONTH, CAR.CAR_ID DESC



WITH CAR_RENTAL_COUNT AS (
    -- 자동차별 총 대여 횟수 구하기
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
SELECT 
    MONTH(START_DATE) AS MONTH, 
    R.CAR_ID, 
    COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY R
JOIN CAR_RENTAL_COUNT C ON R.CAR_ID = C.CAR_ID
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH(START_DATE), R.CAR_ID
ORDER BY MONTH(START_DATE), R.CAR_ID DESC;