SELECT YEAR(ED.DIFFERENTIATION_DATE) AS YEAR 
       ,A.MAX_SIZE - ED.SIZE_OF_COLONY AS YEAR_DEV
       ,ED.ID
FROM ECOLI_DATA ED
JOIN (
   SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
   FROM ECOLI_DATA
   GROUP BY YEAR(DIFFERENTIATION_DATE)
) A
ON YEAR(ED.DIFFERENTIATION_DATE) = A.YEAR
ORDER BY YEAR, YEAR_DEV
;