SELECT DISTINCT(CRCRH.CAR_ID)
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
JOIN CAR_RENTAL_COMPANY_CAR CRCC
    ON CRCRH.CAR_ID = CRCC.CAR_ID
WHERE CAR_TYPE = '세단'
AND TO_CHAR(START_DATE, 'MM') = '10'
ORDER BY CRCRH.CAR_ID DESC
;