SELECT BOOK_ID, TO_CHAR(PUBLISHED_DATE, 'YYYY-MM-DD') AS "PUBLISHED_DATE"
FROM BOOK
WHERE CATEGORY = '인문'
AND PUBLISHED_DATE 
    BETWEEN TO_DATE('2021-01','YYYY-MM')
    AND TO_DATE('2021-12','YYYY-MM')
ORDER BY PUBLISHED_DATE
;