SELECT ugb.TITLE
       ,ugb.BOARD_ID
       ,ugr.REPLY_ID
       ,ugr.WRITER_ID
       ,ugr.CONTENTS
       ,TO_CHAR(ugr.CREATED_DATE, 'YYYY-MM-DD')
FROM USED_GOODS_REPLY ugr, USED_GOODS_BOARD ugb
WHERE ugr.BOARD_ID = ugb.BOARD_ID
AND TO_CHAR(ugb.CREATED_DATE, 'YYYY-MM') = '2022-10'
ORDER BY ugr.CREATED_DATE, ugb.TITLE
;
